/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.CustomerDirectory;
import Model.Order;
import Model.OrderDirectory;
import Model.ProductDirectory;
import Utils.JudCondition;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class AddOrder extends javax.swing.JPanel {

    /**
     * Creates new form AddOrder
     */
    private JPanel MainMenu;
    private OrderDirectory orderdirectory;
    private CustomerDirectory customerdirectory;
    private ProductDirectory productdirectory;
    public AddOrder(JPanel mainmenu, OrderDirectory directoryo,CustomerDirectory directoryc, ProductDirectory directoryp) {
        initComponents();
        MainMenu=mainmenu;
        orderdirectory=directoryo;
        customerdirectory = directoryc;
        productdirectory = directoryp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldCustomerid = new javax.swing.JTextField();
        fieldDate = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        boxProduct = new javax.swing.JComboBox<>();
        boxStatus = new javax.swing.JComboBox<>();
        boxMethod = new javax.swing.JComboBox<>();
        boxType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        fieldProductid = new javax.swing.JTextField();

        fieldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDateActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel1.setText("Add  a  Order");

        jLabel2.setText("Product ID");

        jLabel3.setText("Date");

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        jLabel4.setText("Type");

        jLabel5.setText("Payment Method");

        jLabel6.setText("Status");

        jLabel7.setText("Product");

        boxProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coffee", "Tea", "Sandwish", "Pastry", "Dessert" }));
        boxProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxProductActionPerformed(evt);
            }
        });

        boxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Preparing", "Ready", "Completed" }));
        boxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxStatusActionPerformed(evt);
            }
        });

        boxMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card", "Mobile" }));
        boxMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMethodActionPerformed(evt);
            }
        });

        boxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dine-in", "Takeout", "Pickup" }));
        boxType.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                boxTypeComponentAdded(evt);
            }
        });
        boxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTypeActionPerformed(evt);
            }
        });

        jLabel8.setText("Customer ID");

        fieldProductid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldProductidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))))
                .addContainerGap(228, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxType, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Save)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fieldCustomerid, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                        .addComponent(fieldProductid)))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fieldCustomerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldProductid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(boxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(boxMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(boxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(110, 110, 110)
                .addComponent(Save)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boxProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxProductActionPerformed

    private void boxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxStatusActionPerformed

    private void boxMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxMethodActionPerformed

    private void boxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTypeActionPerformed

    private void fieldProductidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldProductidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldProductidActionPerformed

    private void boxTypeComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_boxTypeComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTypeComponentAdded

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        
    String customerId = fieldCustomerid.getText();
    String productId = fieldProductid.getText();
    Date date = new Date(); 
    String orderType = (String) boxType.getSelectedItem();
    String paymentMethod = (String) boxMethod.getSelectedItem();
    String orderStatus = (String) boxStatus.getSelectedItem();
    String productName = (String) boxProduct.getSelectedItem(); 
   
    if (customerId.isBlank() || productId.isBlank() 
        || productName.isBlank()) {
    JOptionPane.showMessageDialog(this, "All fields are mandatory", "Error", JOptionPane.ERROR_MESSAGE);
} 

else if (!JudCondition.isNumeric(customerId) || !JudCondition.isNumeric(productId)) {
    JOptionPane.showMessageDialog(this, "The content you entered is invalid", "Error", JOptionPane.ERROR_MESSAGE);
} 
else if (customerdirectory.searchCustomer(customerId)==null||productdirectory.searchProduct(productId)==null){
    JOptionPane.showMessageDialog(this, "Please entered the right id", "Error", JOptionPane.ERROR_MESSAGE);
}
else {
 
    JOptionPane.showMessageDialog(this, "Successfully created!", "Create", JOptionPane.INFORMATION_MESSAGE);

    Order o = orderdirectory.addOrder( productdirectory.searchProduct(productId),customerdirectory.searchCustomer(customerId)); 
    
    o.setCustomerId(customerId);
    o.setProductId(productId);  
    o.setTime(date);
    o.setType(orderType);
    o.setPaymethod(paymentMethod);
    o.setStatus(orderStatus);
    o.setProductname(productName); 

    fieldCustomerid.setText("");
    fieldProductid.setText("");
    fieldDate.setText("");
    boxType.setSelectedIndex(0);
    boxMethod.setSelectedIndex(0);
    boxStatus.setSelectedIndex(0);
    boxProduct.setSelectedIndex(0);
    }//GEN-LAST:event_SaveActionPerformed
    }
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        MainMenu.remove(this);
        CardLayout layout=(CardLayout) MainMenu.getLayout();
        layout.previous(MainMenu);
        
        
    }//GEN-LAST:event_BackActionPerformed

    private void fieldDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDateActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Save;
    private javax.swing.JComboBox<String> boxMethod;
    private javax.swing.JComboBox<String> boxProduct;
    private javax.swing.JComboBox<String> boxStatus;
    private javax.swing.JComboBox<String> boxType;
    private javax.swing.JTextField fieldCustomerid;
    private javax.swing.JTextField fieldDate;
    private javax.swing.JTextField fieldProductid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
