/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.CustomerDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class CustomerMngJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerMngJPanel
     */
    private JPanel MainMenu;
    private CustomerDirectory customerdirectory; 
    public CustomerMngJPanel(JPanel mainmenu, CustomerDirectory directory) {
        initComponents();
        MainMenu=mainmenu;
        customerdirectory=directory;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeleteCustomer = new javax.swing.JButton();
        SearchCustomer = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        ViewCustomer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        AddCustmoer = new javax.swing.JButton();

        DeleteCustomer.setText("Delete");
        DeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCustomerActionPerformed(evt);
            }
        });

        SearchCustomer.setText("Search");
        SearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCustomerActionPerformed(evt);
            }
        });

        ViewCustomer.setText("View");
        ViewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCustomerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel1.setText("Customer");

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer ID", "Firstname", "Lastname", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        AddCustmoer.setText("Add ");
        AddCustmoer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustmoerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DeleteCustomer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(AddCustmoer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ViewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCustmoer)
                    .addComponent(ViewCustomer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteCustomer)
                    .addComponent(SearchCustomer)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchCustomerActionPerformed

    private void ViewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCustomerActionPerformed
  int selectedRow=tblCustomer.getSelectedRow();
        if(selectedRow>=0){
            
            // 获取选中行的Product ID（第1列）
             String productId = (String)tblCustomer.getValueAt(selectedRow, 1);
            // 通过ID查找Product对象
             Customer selectedProduct = CustomerDirectory.searchCustomer(productId);
           if(selectedProduct != null){
            ViewProduct panel = new ViewProduct(MainMenu, customerdirectory, selectedProduct);
            MainMenu.add("ViewProduct", panel);
            CardLayout layout = (CardLayout) MainMenu.getLayout();
            layout.next(MainMenu);
        } else {
            JOptionPane.showMessageDialog(this, "Product not found!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a product from the list", "Warning", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_ViewCustomerActionPerformed

    private void AddCustmoerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustmoerActionPerformed
        AddCustomer panel=new AddCustomer(MainMenu,customerdirectory);
        MainMenu.add("AddCustomer",panel);
        
        CardLayout layout=(CardLayout)MainMenu.getLayout();
        layout.next(MainMenu); 
    }//GEN-LAST:event_AddCustmoerActionPerformed

    private void DeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCustomerActionPerformed
            int selectedRow = tblCustomer.getSelectedRow();
        if(selectedRow >= 0){
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure to delete the customer?", 
                                                        "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            String customerId = (String)tblCustomer.getValueAt(selectedRow, 0);
            Customer selectedProduct = customerdirectory.searchCustomer(customerId);
            
            if(selectedProduct != null){
                customerdirectory.deleteCustomer(selectedProduct);
                populateTable();
                JOptionPane.showMessageDialog(this, "customer deleted successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "customer not found!");
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select an customer to delete!");
    } 
    }//GEN-LAST:event_DeleteCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCustmoer;
    private javax.swing.JButton DeleteCustomer;
    private javax.swing.JButton SearchCustomer;
    private javax.swing.JButton ViewCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblCustomer;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblCustomer.getModel();
         model.setRowCount(0);
    for(Customer c : customerdirectory.getCustomerlist()){
    Object[] row = new Object[4];
    row[0] = c.getId();                         
    row[1] = c.getFirstname();      
    row[2] = c.getLastname();
    row[3] = c.getContact(); 
    model.addRow(row);                  
}}
    @Override
    public void setVisible(boolean visible) {
    super.setVisible(visible);
    if (visible) {
        populateTable(); // 每次显示时刷新
    }
        
    }
    
    
}
