/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.OrderDirectory;
import Model.ProductDirectory;
import Model.CustomerDirectory;
import java.awt.CardLayout;

/**
 *
 * @author DELL
 */
public class MainJFrame extends javax.swing.JFrame {
    ProductDirectory productdirectory;
    OrderDirectory orderdirectory;
    CustomerDirectory customerdirectory;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        btnProductMng = new javax.swing.JButton();
        btnOrderMng = new javax.swing.JButton();
        btnCustomerMng = new javax.swing.JButton();
        MainMenu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        btnProductMng.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnProductMng.setText("Product Management");
        btnProductMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductMngActionPerformed(evt);
            }
        });

        btnOrderMng.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnOrderMng.setText("Order Management");
        btnOrderMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderMngActionPerformed(evt);
            }
        });

        btnCustomerMng.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnCustomerMng.setText("Customer Management");
        btnCustomerMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerMngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCustomerMng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrderMng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProductMng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btnProductMng, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnOrderMng, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnCustomerMng, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        MainMenu.setBackground(new java.awt.Color(255, 204, 153));
        MainMenu.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(MainMenu);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductMngActionPerformed
        ProductMngJPanel panel=new ProductMngJPanel(MainMenu,productdirectory);
        MainMenu.add("ProductMngJPanel",panel);
        
        CardLayout layout=(CardLayout)MainMenu.getLayout();
        layout.next(MainMenu);  // TODO add your handling code here:
    }//GEN-LAST:event_btnProductMngActionPerformed

    private void btnOrderMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderMngActionPerformed
        OrderMngJPanel panel=new OrderMngJPanel(MainMenu,orderdirectory);
        MainMenu.add("OrderMngJpanel",panel);
        
        CardLayout layout=(CardLayout)MainMenu.getLayout();
        layout.next(MainMenu);   // TODO add your handling code here:
    }//GEN-LAST:event_btnOrderMngActionPerformed

    private void btnCustomerMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerMngActionPerformed
        CustomerMngJPanel panel=new CustomerMngJPanel(MainMenu,customerdirectory);
        MainMenu.add("CustomerMngJPanel",panel);
        
        CardLayout layout=(CardLayout)MainMenu.getLayout();
        layout.next(MainMenu);  // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerMngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainMenu;
    private javax.swing.JButton btnCustomerMng;
    private javax.swing.JButton btnOrderMng;
    private javax.swing.JButton btnProductMng;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
