/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Customer;
import Model.OrderDirectory;
import Model.ProductDirectory;
import Model.CustomerDirectory;
import Model.Order;
import Model.Product;
import java.awt.CardLayout;
import java.util.Date;

/**
 *
 * @author DELL
 */
public class MainJFrame extends javax.swing.JFrame {
    ProductDirectory productdirectory;
    OrderDirectory orderdirectory;
    CustomerDirectory customerdirectory;
    /**
     * Creates new form MainJFrame
     */
     
    public MainJFrame() {
        initComponents();
        productdirectory = new ProductDirectory();
        orderdirectory = new OrderDirectory();
        customerdirectory = new CustomerDirectory();
        initializeData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        btnProductMng = new javax.swing.JButton();
        btnOrderMng = new javax.swing.JButton();
        btnCustomerMng = new javax.swing.JButton();
        MainMenu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        btnProductMng.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnProductMng.setText("Product Management");
        btnProductMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductMngActionPerformed(evt);
            }
        });

        btnOrderMng.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnOrderMng.setText("Order Management");
        btnOrderMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderMngActionPerformed(evt);
            }
        });

        btnCustomerMng.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnCustomerMng.setText("Customer Management");
        btnCustomerMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerMngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCustomerMng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrderMng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProductMng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btnProductMng, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnOrderMng, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnCustomerMng, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        MainMenu.setBackground(new java.awt.Color(255, 204, 153));
        MainMenu.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(MainMenu);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductMngActionPerformed
        ProductMngJPanel panel=new ProductMngJPanel(MainMenu,productdirectory);
        MainMenu.add("ProductMngJPanel",panel);
        
        CardLayout layout=(CardLayout)MainMenu.getLayout();
        layout.next(MainMenu);  // TODO add your handling code here:
    }//GEN-LAST:event_btnProductMngActionPerformed

    private void btnOrderMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderMngActionPerformed
        OrderMngJPanel panel=new OrderMngJPanel(MainMenu,orderdirectory,customerdirectory,productdirectory);
        MainMenu.add("OrderMngJpanel",panel);
        
        CardLayout layout=(CardLayout)MainMenu.getLayout();
        layout.next(MainMenu);   // TODO add your handling code here:
    }//GEN-LAST:event_btnOrderMngActionPerformed

    private void btnCustomerMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerMngActionPerformed
      CustomerMngJPanel panel = new CustomerMngJPanel(
    MainMenu,
    customerdirectory,
    orderdirectory,
    productdirectory
);

        MainMenu.add("CustomerMngJPanel",panel);
        
        CardLayout layout=(CardLayout)MainMenu.getLayout();
        layout.next(MainMenu);  // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerMngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainMenu;
    private javax.swing.JButton btnCustomerMng;
    private javax.swing.JButton btnOrderMng;
    private javax.swing.JButton btnProductMng;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    private void initializeData() {
    Customer c1 = customerdirectory.addCustomer();
    c1.setId("C001");
    c1.setFirstname("John");
    c1.setLastname("Smith");
    c1.setContact("1234567890");
    
    Customer c2 = customerdirectory.addCustomer();
    c2.setId("C002");
    c2.setFirstname("Alice");
    c2.setLastname("Johnson");
    c2.setContact("2345678901");
   
    Customer c3 = customerdirectory.addCustomer();
    c3.setId("C003");
    c3.setFirstname("Bob");
    c3.setLastname("Brown");
    c3.setContact("3456789012");
    
    Customer c4 = customerdirectory.addCustomer();
    c4.setId("C004");
    c4.setFirstname("Emma");
    c4.setLastname("Davis");
    c4.setContact("4567890123");
   
    Customer c5 = customerdirectory.addCustomer();
    c5.setId("C005");
    c5.setFirstname("Michael");
    c5.setLastname("Wilson");
    c5.setContact("5678901234");
    
    
    Product p1 = productdirectory.addProduct();
    p1.setId("P001");
    p1.setName("Americano");
    p1.setCategory("Coffee");
    p1.setPrice(3.50);
    p1.setNumber(50);
    p1.setPreparetime(3);
    
    
    Product p2 = productdirectory.addProduct();
    p2.setId("P002");
    p2.setName("Latte");
    p2.setCategory("Coffee");
    p2.setPrice(4.50);
    p2.setNumber(30);
    p2.setPreparetime(5);
    
   
    Product p3 = productdirectory.addProduct();
    p3.setId("P003");
    p3.setName("Green Tea");
    p3.setCategory("Tea");
    p3.setPrice(2.50);
    p3.setNumber(40);
    p3.setPreparetime(2);
    
   
    Product p4 = productdirectory.addProduct();
    p4.setId("P004");
    p4.setName("Chicken Sandwich");
    p4.setCategory("Sandwich");
    p4.setPrice(6.50);
    p4.setNumber(25);
    p4.setPreparetime(8);
    
  
    Product p5 = productdirectory.addProduct();
    p5.setId("P005");
    p5.setName("Croissant");
    p5.setCategory("Pastry");
    p5.setPrice(3.00);
    p5.setNumber(35);
    p5.setPreparetime(2);
    
    Product p6 = productdirectory.addProduct();
    p6.setId("P006");
    p6.setName("Chocolate Cake");
    p6.setCategory("Dessert");
    p6.setPrice(5.50);
    p6.setNumber(20);
    p6.setPreparetime(1);
    
    Order o1 = orderdirectory.addOrder(p1, c1);
    o1.setCustomerId("C001");
    o1.setProductId("P001");
    o1.setTime(new Date());
    o1.setType("Dine-in");
    o1.setPaymethod("Card");
    o1.setStatus("Completed");
    o1.setProductname("Americano");
    
    
    Order o2 = orderdirectory.addOrder(p2, c2);
    o2.setCustomerId("C002");
    o2.setProductId("P002");
    o2.setTime(new Date());
    o2.setType("Takeout");
    o2.setPaymethod("Cash");
    o2.setStatus("Ready");
    o2.setProductname("Latte");
    
    Order o3 = orderdirectory.addOrder(p3, c3);
    o3.setCustomerId("C003");
    o3.setProductId("P003");
    o3.setTime(new Date());
    o3.setType("Pickup");
    o3.setPaymethod("Mobile");
    o3.setStatus("Preparing");
    o3.setProductname("Green Tea");
    }
    
    
    
    
    
}
