/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Product;
import Model.ProductDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class ViewProduct extends javax.swing.JPanel {

    /**
     * Creates new form ViewProduct
     */
    private JPanel MainMenu;
    private ProductDirectory productdirectory;
    private Product product;
    public ViewProduct(JPanel container, ProductDirectory productDirectory , Product product1 ) {
        initComponents();
        MainMenu=container;
        productdirectory=productDirectory;
        product=product1;
        
        populateFields();    
        setViewMode();
        refreshTextFields();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldProductname = new javax.swing.JTextField();
        fieldProductID = new javax.swing.JTextField();
        fieldCategory = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        fieldPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fieldNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldPrepTime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel1.setText("View  a  Product");

        jLabel2.setText("Product Name");

        jLabel3.setText("Product ID");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel4.setText("Category");

        jLabel5.setText("Price");

        jLabel6.setText("Number");

        jLabel7.setText("PrepareTime");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)))
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(137, 137, 137)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldProductname)
                                    .addComponent(fieldProductID)
                                    .addComponent(fieldCategory)
                                    .addComponent(fieldPrice)
                                    .addComponent(fieldNumber)
                                    .addComponent(fieldPrepTime, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btnSave)
                        .addGap(158, 158, 158)
                        .addComponent(btnUpdate)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldProductname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fieldPrepTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
            setViewMode();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         MainMenu.remove(this);
        Component[] panelStack=MainMenu.getComponents();
        JPanel lastPanel =(JPanel)panelStack[panelStack.length-1];
        ProductMngJPanel JPanel=(ProductMngJPanel)lastPanel;
        JPanel.populateTable();
        
        CardLayout layout=(CardLayout)MainMenu.getLayout();
        layout.previous(MainMenu);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String category=fieldCategory.getText();
        String number=fieldNumber.getText();
        String prepTime=fieldPrepTime.getText();
        String productID=fieldProductID.getText();
        String price=fieldPrice.getText();
        String pdctname=fieldProductname.getText();   
        
        if (category.isBlank()||number.isBlank()||prepTime.isBlank()||productID.isBlank()||price.isBlank()||pdctname.isBlank()){
            JOptionPane.showMessageDialog(null, "All fields are mandatory");
            return;
        }
        product.setCategory(category);
        product.setId(productID);
        product.setName(pdctname);
        ;   // 转成 int
        product.setPreparetime(Integer.parseInt(prepTime));   
        product.setNumber(Integer.parseInt(prepTime));
        product.setPrice(Double.parseDouble(prepTime));

        JOptionPane.showMessageDialog(null, "Account successfully updated", "warning", JOptionPane.WARNING_MESSAGE);
        
        refreshTextFields();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField fieldCategory;
    private javax.swing.JTextField fieldNumber;
    private javax.swing.JTextField fieldPrepTime;
    private javax.swing.JTextField fieldPrice;
    private javax.swing.JTextField fieldProductID;
    private javax.swing.JTextField fieldProductname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    private void populateFields() {
     if(product!=null){
    fieldCategory.setText(product.getCategory());
    fieldProductID.setText(product.getId());
    fieldProductname.setText(product.getName());
    fieldPrepTime.setText(String.valueOf(product.getPreparetime()));
    fieldNumber.setText(String.valueOf(product.getNumber()));
    fieldPrice.setText(String.valueOf(product.getPrice()));
     }
    }

    private void setViewMode() {
      fieldCategory.setEnabled(true);
fieldProductID.setEnabled(true);
fieldProductname.setEnabled(true);
fieldPrepTime.setEnabled(true);
fieldNumber.setEnabled(true);
fieldPrice.setEnabled(true);

btnSave.setEnabled(true);
btnUpdate.setEnabled(false);

    }

    private void refreshTextFields() {
      fieldCategory.setEnabled(false);
fieldProductID.setEnabled(false);
fieldProductname.setEnabled(false);
fieldPrepTime.setEnabled(false);
fieldNumber.setEnabled(false);
fieldPrice.setEnabled(false);

btnSave.setEnabled(false);
btnUpdate.setEnabled(true);

    }
}
