/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePersonJPanel
     */
    
    Person person;
    public CreatePersonJPanel(Person p) {
        initComponents();
        person=p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPersonName = new javax.swing.JLabel();
        lblPersonAge = new javax.swing.JLabel();
        fieldPersonName = new javax.swing.JTextField();
        fieldPersonAge = new javax.swing.JTextField();
        lblPersonGender = new javax.swing.JLabel();
        fieldPersonGender = new javax.swing.JTextField();
        fieldPersonEmail = new javax.swing.JTextField();
        fieldPersonPhone = new javax.swing.JTextField();
        lblPersonEmail = new javax.swing.JLabel();
        lblPersonPhone = new javax.swing.JLabel();
        CreatePersonSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 153));

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblTitle.setText("Create Person");

        lblPersonName.setText("Name");

        lblPersonAge.setText("Age");

        lblPersonGender.setText("Gender");

        fieldPersonEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPersonEmailActionPerformed(evt);
            }
        });

        fieldPersonPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPersonPhoneActionPerformed(evt);
            }
        });

        lblPersonEmail.setText("Email");

        lblPersonPhone.setText("Phone");

        CreatePersonSave.setText("Save");
        CreatePersonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePersonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPersonAge)
                    .addComponent(lblPersonName)
                    .addComponent(lblPersonGender)
                    .addComponent(lblPersonEmail)
                    .addComponent(lblPersonPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldPersonName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldPersonAge, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldPersonGender, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldPersonEmail)
                    .addComponent(fieldPersonPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(lblTitle)
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CreatePersonSave)
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblTitle)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPersonName)
                            .addComponent(fieldPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblPersonAge))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(fieldPersonAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPersonGender)
                    .addComponent(fieldPersonGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPersonEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPersonEmail))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPersonPhone)
                    .addComponent(fieldPersonPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(CreatePersonSave)
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldPersonPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPersonPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPersonPhoneActionPerformed

    private void fieldPersonEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPersonEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPersonEmailActionPerformed

    private void CreatePersonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePersonSaveActionPerformed
        // TODO add your handling code here:
        // Retrieve user input from the text fields
        String name = fieldPersonName.getText();
        String age = fieldPersonAge.getText();
        String email = fieldPersonEmail.getText();
        String gender = fieldPersonGender.getText();
        String phone = fieldPersonPhone.getText();
          //Store the retrieved data into the Person object
        person.setName(name);
        person.setAge(age);
        person.setEmail(email);
        person.setGender(gender);
        person.setPhone(phone);
        
        JOptionPane.showMessageDialog(this,"Successfully saved!");
             //Clear the text fields for the next input
        fieldPersonName.setText("");
        fieldPersonName.setText("");
        fieldPersonAge.setText("");
        fieldPersonEmail.setText("");
        fieldPersonGender.setText("");
        fieldPersonPhone.setText("");
 
    }//GEN-LAST:event_CreatePersonSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreatePersonSave;
    private javax.swing.JTextField fieldPersonAge;
    private javax.swing.JTextField fieldPersonEmail;
    private javax.swing.JTextField fieldPersonGender;
    private javax.swing.JTextField fieldPersonName;
    private javax.swing.JTextField fieldPersonPhone;
    private javax.swing.JLabel lblPersonAge;
    private javax.swing.JLabel lblPersonEmail;
    private javax.swing.JLabel lblPersonGender;
    private javax.swing.JLabel lblPersonName;
    private javax.swing.JLabel lblPersonPhone;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
