/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.HomeAddress;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class CreateHomeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateHomeJPanel
     */
    HomeAddress homeaddress;
    public CreateHomeJPanel( HomeAddress h) {
        initComponents();
        homeaddress=h;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldHomeStreet = new javax.swing.JTextField();
        fieldHomeCity = new javax.swing.JTextField();
        fieldHomeState = new javax.swing.JTextField();
        fieldHomeName = new javax.swing.JTextField();
        fieldHomezipCode = new javax.swing.JTextField();
        CreateHomeSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel1.setText("Create Home Address");

        jLabel2.setText("Street");

        jLabel3.setText("City");

        jLabel4.setText("State");

        jLabel5.setText("Name");

        jLabel6.setText("zipCode");

        fieldHomeState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHomeStateActionPerformed(evt);
            }
        });

        fieldHomezipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHomezipCodeActionPerformed(evt);
            }
        });

        CreateHomeSave.setText("Save");
        CreateHomeSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateHomeSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1)
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldHomezipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldHomeName, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fieldHomeStreet)
                                        .addComponent(fieldHomeCity)
                                        .addComponent(fieldHomeState, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))))))
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(CreateHomeSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(fieldHomeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldHomeStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldHomeCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldHomeState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldHomezipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(CreateHomeSave)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldHomeStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHomeStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHomeStateActionPerformed

    private void fieldHomezipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHomezipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHomezipCodeActionPerformed

    private void CreateHomeSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateHomeSaveActionPerformed
        // TODO add your handling code here:
        String name=fieldHomeName.getText();
        String city=fieldHomeCity.getText();
        String state=fieldHomeState.getText();
        String street=fieldHomeStreet.getText();
        String zipCode=fieldHomezipCode.getText();
       
       homeaddress.setName(name);
       homeaddress.setState(state);
       homeaddress.setCity(city);
       homeaddress.setStreet(street);
       homeaddress.setZipCode(zipCode);
        
        
        JOptionPane.showMessageDialog(this,"Successfully saved!");
        
        fieldHomeCity.setText("");
        fieldHomeName.setText("");
        fieldHomeState.setText("");
        fieldHomeStreet.setText("");
        fieldHomezipCode.setText("");

        
        
        
        
        
    }//GEN-LAST:event_CreateHomeSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateHomeSave;
    private javax.swing.JTextField fieldHomeCity;
    private javax.swing.JTextField fieldHomeName;
    private javax.swing.JTextField fieldHomeState;
    private javax.swing.JTextField fieldHomeStreet;
    private javax.swing.JTextField fieldHomezipCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
