/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Model.Person;
/**
 *
 * @author DELL
 */
public class ViewPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPersonJPanel
     */
    Person person;
    public ViewPersonJPanel(Person p) {
        initComponents();
        person =p;
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPersonEmail = new javax.swing.JLabel();
        lblPersonPhone = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblPersonName = new javax.swing.JLabel();
        lblPersonAge = new javax.swing.JLabel();
        fieldPersonName = new javax.swing.JTextField();
        fieldPersonAge = new javax.swing.JTextField();
        lblPersonGender = new javax.swing.JLabel();
        fieldPersonGender = new javax.swing.JTextField();
        fieldPersonEmail = new javax.swing.JTextField();
        fieldPersonPhone = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));

        lblPersonEmail.setText("Email");

        lblPersonPhone.setText("Phone");

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblTitle.setText("View Person");

        lblPersonName.setText("Name");

        lblPersonAge.setText("Age");

        lblPersonGender.setText("Gender");

        fieldPersonEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPersonEmailActionPerformed(evt);
            }
        });

        fieldPersonPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPersonPhoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPersonAge)
                            .addComponent(lblPersonName)
                            .addComponent(lblPersonGender)
                            .addComponent(lblPersonEmail)
                            .addComponent(lblPersonPhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldPersonName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldPersonAge, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldPersonGender, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldPersonEmail)
                            .addComponent(fieldPersonPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPersonName)
                            .addComponent(fieldPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblPersonAge))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(fieldPersonAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPersonGender)
                    .addComponent(fieldPersonGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPersonEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPersonEmail))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPersonPhone)
                    .addComponent(fieldPersonPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldPersonEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPersonEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPersonEmailActionPerformed

    private void fieldPersonPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPersonPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPersonPhoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldPersonAge;
    private javax.swing.JTextField fieldPersonEmail;
    private javax.swing.JTextField fieldPersonGender;
    private javax.swing.JTextField fieldPersonName;
    private javax.swing.JTextField fieldPersonPhone;
    private javax.swing.JLabel lblPersonAge;
    private javax.swing.JLabel lblPersonEmail;
    private javax.swing.JLabel lblPersonGender;
    private javax.swing.JLabel lblPersonName;
    private javax.swing.JLabel lblPersonPhone;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    private void display() {
         fieldPersonName.setText(person.getName());
         fieldPersonEmail.setText(person.getEmail());
          fieldPersonGender.setText(person.getGender());
          fieldPersonAge.setText(person.getAge());
          fieldPersonPhone.setText(person.getPhone());
          
    }
}
